name: dhilla
author: Faris Nasution <nasution.faris@gmail.com>
version: 0.0.1
description: A simple web framework.
dependencies:
  http_server: any
  mongo_dart: any
  transformer: any
  unittest: any
