name: dhilla
author: Faris Nasution <nasution.faris@gmail.com>
version: 0.0.1
homepage: https://github.com/farisnasution/dhilla
description: A simple wrapper around Dart's vanilla HttpServer
dependencies:
  http_server: any
  transformer: any
  unittest: any
